import { AccountDefinition } from './types';

export const US_GAAP_SERVICE_CHART_OF_ACCOUNTS: AccountDefinition[] = [
  // 1000 - ASSETS
  // 1100 - Current Assets: Cash & Cash Equivalents
  {
    code: '1010',
    name: 'Operating Checking Account (Mercury / Chase / SVB)',
    namePt: 'Conta Corrente Operacional',
    nameEs: 'Cuenta Corriente Operativa',
    type: 'ASSET',
    subType: 'CASH_AND_CASH_EQUIVALENTS',
    description: 'Primary operational checking account for disbursements and receipts.',
  },
  {
    code: '1020',
    name: 'Payroll Checking Account',
    namePt: 'Conta Corrente de Folha de Pagamento',
    nameEs: 'Cuenta Corriente de Nómina',
    type: 'ASSET',
    subType: 'CASH_AND_CASH_EQUIVALENTS',
    description: 'Dedicated account for employee wages and tax withholdings.',
  },
  {
    code: '1030',
    name: 'High-Yield Business Savings / Treasury',
    namePt: 'Poupança Empresarial / Tesouraria',
    nameEs: 'Ahorros Empresariales / Tesorería',
    type: 'ASSET',
    subType: 'CASH_AND_CASH_EQUIVALENTS',
    description: 'Short-term treasury and yield accounts for runway capital.',
  },
  // 1200 - Current Assets: Accounts Receivable
  {
    code: '1200',
    name: 'Accounts Receivable (A/R)',
    namePt: 'Contas a Receber (Clientes)',
    nameEs: 'Cuentas por Cobrar (Clientes)',
    type: 'ASSET',
    subType: 'ACCOUNTS_RECEIVABLE',
    description: 'Uncollected invoiced billings for completed services.',
  },
  {
    code: '1250',
    name: 'Allowance for Doubtful Accounts',
    namePt: 'Provisão para Devedores Duvidosos',
    nameEs: 'Provisión para Cuentas Incobrables',
    type: 'ASSET',
    subType: 'ALLOWANCE_FOR_DOUBTFUL_ACCOUNTS',
    description: 'Contra-asset account estimating uncollectible invoices.',
  },
  {
    code: '1300',
    name: 'Prepaid Expenses & Subscriptions',
    namePt: 'Despesas Pré-Pagas e Assinaturas Anuais',
    nameEs: 'Gastos Prepagados y Suscripciones',
    type: 'ASSET',
    subType: 'PREPAID_EXPENSES',
    description: 'Annual software licenses, insurance and advance payments.',
  },
  {
    code: '1400',
    name: 'Security Deposits & Retainers Paid',
    namePt: 'Depósitos de Garantia',
    nameEs: 'Depósitos de Garantía',
    type: 'ASSET',
    subType: 'SECURITY_DEPOSITS',
    description: 'Office lease deposits and utility reserves.',
  },
  // 1500 - Non-Current Assets: Fixed Assets
  {
    code: '1510',
    name: 'Computer Equipment & Hardware',
    namePt: 'Equipamentos de Informática e Hardware',
    nameEs: 'Equipos de Cómputo y Hardware',
    type: 'ASSET',
    subType: 'PROPERTY_PLANT_EQUIPMENT',
    description: 'Laptops, servers, workstations above capitalization threshold.',
  },
  {
    code: '1590',
    name: 'Accumulated Depreciation - Equipment',
    namePt: 'Depreciação Acumulada - Equipamentos',
    nameEs: 'Depreciación Acumulada - Equipos',
    type: 'ASSET',
    subType: 'ACCUMULATED_DEPRECIATION',
    description: 'Contra-asset for MACRS / straight-line depreciation.',
  },

  // 2000 - LIABILITIES
  // 2100 - Current Liabilities
  {
    code: '2010',
    name: 'Accounts Payable (A/P)',
    namePt: 'Contas a Pagar (Fornecedores)',
    nameEs: 'Cuentas por Pagar (Proveedores)',
    type: 'LIABILITY',
    subType: 'ACCOUNTS_PAYABLE',
    description: 'Outstanding bills from vendors, contractors, and SaaS tools.',
  },
  {
    code: '2020',
    name: 'Corporate Credit Cards Payable (Ramp / Brex / Amex)',
    namePt: 'Cartões Corporativos a Pagar',
    nameEs: 'Tarjetas Corporativas por Pagar',
    type: 'LIABILITY',
    subType: 'ACCOUNTS_PAYABLE',
    description: 'Outstanding balance on corporate cards awaiting settlement.',
  },
  {
    code: '2100',
    name: 'Unearned Revenue / Client Retainers',
    namePt: 'Receita Antecipada / Retainers a Executar',
    nameEs: 'Ingresos Diferidos / Anticipos de Clientes',
    type: 'LIABILITY',
    subType: 'UNEARNED_REVENUE_RETAINERS',
    description: 'Upfront retainer fees received before service delivery.',
  },
  {
    code: '2210',
    name: 'Federal Payroll Taxes Payable (941 / FICA / FIT)',
    namePt: 'Impostos de Folha Federais a Recolher',
    nameEs: 'Impuestos Federales de Nómina por Pagar',
    type: 'LIABILITY',
    subType: 'PAYROLL_TAXES_PAYABLE',
    description: 'Withheld FICA (Social Security & Medicare) and Federal Income Tax.',
  },
  {
    code: '2220',
    name: 'State & Local Payroll Taxes Payable (SIT / SUTA)',
    namePt: 'Impostos de Folha Estaduais a Recolher',
    nameEs: 'Impuestos Estatales de Nómina por Pagar',
    type: 'LIABILITY',
    subType: 'PAYROLL_TAXES_PAYABLE',
    description: 'State unemployment and state income tax withholdings.',
  },
  {
    code: '2300',
    name: 'Sales Tax Payable',
    namePt: 'Sales Tax Estadual/Municipal a Recolher',
    nameEs: 'Impuesto sobre Ventas por Pagar',
    type: 'LIABILITY',
    subType: 'SALES_TAX_PAYABLE',
    description: 'Sales tax collected on taxable services pending remittance.',
  },

  // 3000 - EQUITY
  {
    code: '3010',
    name: "Owner's Equity / Common Stock",
    namePt: 'Capital Social / Aportes dos Sócios',
    nameEs: 'Capital Social / Aportes de Socios',
    type: 'EQUITY',
    subType: 'OWNERS_EQUITY',
    description: 'Initial and subsequent capital contributions by founders.',
  },
  {
    code: '3020',
    name: "Owner's Draw / Distributions",
    namePt: 'Distribuição de Lucros / Retiradas',
    nameEs: 'Distribución de Utilidades / Retiros',
    type: 'EQUITY',
    subType: 'OWNERS_DRAW',
    description: 'Partner draws and S-Corp shareholder distributions.',
  },
  {
    code: '3100',
    name: 'Retained Earnings',
    namePt: 'Lucros / Prejuízos Acumulados',
    nameEs: 'Utilidades Retenidas / Resultados Acumulados',
    type: 'EQUITY',
    subType: 'RETAINED_EARNINGS',
    description: 'Cumulative net profit from prior periods not distributed.',
  },

  // 4000 - REVENUE (SERVICE-BASED)
  {
    code: '4010',
    name: 'Consulting & Advisory Services Revenue',
    namePt: 'Receita de Serviços de Consultoria',
    nameEs: 'Ingresos por Servicios de Consultoría',
    type: 'REVENUE',
    subType: 'SERVICE_REVENUE_HOURLY',
    description: 'Hourly and fixed-rate strategic consulting engagements.',
  },
  {
    code: '4020',
    name: 'Software Engineering & IT Services Revenue',
    namePt: 'Receita de Engenharia de Software e TI',
    nameEs: 'Ingresos por Ingeniería de Software y TI',
    type: 'REVENUE',
    subType: 'SERVICE_REVENUE_FIXED_FEE',
    description: 'Custom software development, implementation and support fees.',
  },
  {
    code: '4030',
    name: 'Monthly Client Retainers (Recurring Services)',
    namePt: 'Honorários Mensais Recorrentes (Retainers)',
    nameEs: 'Honorarios Mensuales Recurrentes (Retainers)',
    type: 'REVENUE',
    subType: 'SERVICE_REVENUE_RETAINER',
    description: 'Predictable recurring monthly service contracts.',
  },
  {
    code: '4040',
    name: 'Managed Services & Support Subscriptions',
    namePt: 'Serviços Gerenciados e Suporte Contínuo',
    nameEs: 'Servicios Gestionados y Soporte Continuo',
    type: 'REVENUE',
    subType: 'SERVICE_REVENUE_SUBSCRIPTION',
    description: 'SLA-backed monthly maintenance subscriptions.',
  },
  {
    code: '4900',
    name: 'Interest & Treasury Income',
    namePt: 'Receitas Financeiras e Rendimentos',
    nameEs: 'Ingresos Financieros y Rendimientos',
    type: 'REVENUE',
    subType: 'OTHER_INCOME',
    description: 'Yield from savings accounts and treasury bills.',
  },

  // 5000 - COST OF SERVICES (DIRECT PROJECT COSTS)
  {
    code: '5010',
    name: 'Direct Project Labor (Internal Team Billable Hours)',
    namePt: 'Custo de Mão de Obra Direta dos Projetos',
    nameEs: 'Costo de Mano de Obra Directa de Proyectos',
    type: 'COST_OF_SERVICE',
    subType: 'DIRECT_LABOR_SERVICE',
    description: 'Wages allocated directly to client billable hours.',
  },
  {
    code: '5020',
    name: 'Subcontractor & 1099 Contractor Fees',
    namePt: 'Honorários de Prestadores 1099 Subcontratados',
    nameEs: 'Honorarios de Subcontratistas 1099',
    type: 'COST_OF_SERVICE',
    subType: 'SUBCONTRACTOR_EXPENSE',
    description: 'Independent contractor expenses directly tied to client delivery.',
  },
  {
    code: '5030',
    name: 'Direct Project Cloud Infrastructure & Licenses',
    namePt: 'Custos Diretos de Infraestrutura Cloud por Projeto',
    nameEs: 'Costos Directos de Infraestructura Cloud por Proyecto',
    type: 'COST_OF_SERVICE',
    subType: 'DIRECT_SOFTWARE_PROJECT_COSTS',
    description: 'AWS/GCP/Azure compute and API fees dedicated to specific clients.',
  },

  // 6000 - OPERATING EXPENSES (SG&A)
  {
    code: '6010',
    name: 'Executive & Admin Salaries',
    namePt: 'Salários Administrativos e Executivos',
    nameEs: 'Sueldos Administrativos y Ejecutivos',
    type: 'EXPENSE',
    subType: 'PAYROLL_WAGES',
    description: 'Non-billable administrative, HR, and managerial payroll.',
  },
  {
    code: '6020',
    name: 'Employer Payroll Taxes (FICA, FUTA, SUTA)',
    namePt: 'Encargos de Folha do Empregador',
    nameEs: 'Impuestos de Nómina a Cargo del Empleador',
    type: 'EXPENSE',
    subType: 'PAYROLL_TAXES_EMPLOYER',
    description: "Employer's share of Medicare, Social Security, and unemployment.",
  },
  {
    code: '6030',
    name: 'Employee Health Insurance & Benefits',
    namePt: 'Plano de Saúde e Benefícios dos Empregados',
    nameEs: 'Seguro Médico y Beneficios de Empleados',
    type: 'EXPENSE',
    subType: 'EMPLOYEE_BENEFITS',
    description: 'Medical, dental, 401(k) matching, and wellness stipends.',
  },
  {
    code: '6100',
    name: 'Software, SaaS & Productivity Tools',
    namePt: 'Softwares e Ferramentas SaaS Operacionais',
    nameEs: 'Software y Herramientas SaaS Operativas',
    type: 'EXPENSE',
    subType: 'SOFTWARE_AND_SAAS',
    description: 'GitHub, Slack, Google Workspace, Figma, Notion, Linear.',
  },
  {
    code: '6200',
    name: 'Marketing, Lead Gen & Advertising',
    namePt: 'Marketing, Captação de Clientes e Publicidade',
    nameEs: 'Marketing, Captación de Clientes y Publicidad',
    type: 'EXPENSE',
    subType: 'MARKETING_AND_ADVERTISING',
    description: 'Google Ads, LinkedIn campaigns, website development.',
  },
  {
    code: '6300',
    name: 'Legal, Accounting & CPA Professional Fees',
    namePt: 'Honorários de Advogados e Contadores (CPA)',
    nameEs: 'Honorarios Legales y Contables (CPA)',
    type: 'EXPENSE',
    subType: 'PROFESSIONAL_FEES_LEGAL_CPA',
    description: 'Corporate filings, tax prep, legal counsel, registered agent fees.',
  },
  {
    code: '6400',
    name: 'Business Insurance (General Liability & E&O)',
    namePt: 'Seguros Empresariais (E&O e Responsabilidade)',
    nameEs: 'Seguros Empresariales (E&O y Responsabilidad)',
    type: 'EXPENSE',
    subType: 'INSURANCE_GENERAL_LIABILITY_E_AND_O',
    description: 'Errors & Omissions, Cyber Liability, and General Liability insurance.',
  },
  {
    code: '6500',
    name: 'Payment Processing & Bank Wire Fees',
    namePt: 'Taxas Bancárias e de Processamento (Stripe/ACH)',
    nameEs: 'Tarifas Bancarias y de Procesamiento (Stripe/ACH)',
    type: 'EXPENSE',
    subType: 'BANK_AND_PAYMENT_FEES',
    description: 'Stripe card fees, ACH transfer fees, wire fees.',
  },
];
