import { BankFeedTransaction } from './smart-reconciliation-engine';

export interface ConnectedBankItem {
  id: string;
  name: string;
  account: string;
  accountNumberMasked: string;
  balance: number;
  status: string;
  lastSync: string;
}

export class CompanyBankFeedEngine {
  public static getConnectedBanks(companyId: string, legalName?: string): ConnectedBankItem[] {
    const isMilla = companyId.includes('milla') || (legalName && legalName.toLowerCase().includes('milla'));
    const isHorizon = companyId.includes('002') || (legalName && legalName.toLowerCase().includes('horizon'));
    const isApexDelaware = companyId.includes('003') || (legalName && legalName.toLowerCase().includes('delaware'));

    if (isMilla) {
      return [
        {
          id: 'truist',
          name: 'Truist Bank (Commercial)',
          account: 'Operating Checking Account (••••9102)',
          accountNumberMasked: '••••9102',
          balance: 118500.00,
          status: 'Online (Plaid Sync)',
          lastSync: 'Em tempo real',
        },
        {
          id: 'chase-ga',
          name: 'JPMorgan Chase (Georgia)',
          account: 'Business Money Market & Payroll (••••4418)',
          accountNumberMasked: '••••4418',
          balance: 57595.84,
          status: 'Online (Direct Feed)',
          lastSync: 'Há 1 min',
        },
      ];
    }

    if (isHorizon) {
      return [
        {
          id: 'mercury-fl',
          name: 'Mercury Bank (Treasury)',
          account: 'FinTech Treasury Yield (••••1029)',
          accountNumberMasked: '••••1029',
          balance: 224000.00,
          status: 'Online (API Feed)',
          lastSync: 'Em tempo real',
        },
      ];
    }

    if (isApexDelaware) {
      return [
        {
          id: 'chase-de',
          name: 'JPMorgan Chase (Delaware Corp)',
          account: 'Corporate Treasury Vault (••••9920)',
          accountNumberMasked: '••••9920',
          balance: 540000.00,
          status: 'Online (FedNow Sync)',
          lastSync: 'Em tempo real',
        },
      ];
    }

    // Default: Apex CleanOps & Cloud Tech LLC (TX)
    return [
      {
        id: 'chase-tx',
        name: 'JPMorgan Chase (Texas)',
        account: 'Business Operating Checking (••••4819)',
        accountNumberMasked: '••••4819',
        balance: 382000.00,
        status: 'Online (Plaid Core)',
        lastSync: 'Há 2 min',
      },
    ];
  }

  public static getBankFeedTransactions(
    companyId: string,
    legalName?: string,
    fiscalYear?: number,
    selectedMonths?: number[]
  ): BankFeedTransaction[] {
    const isMilla = companyId.includes('milla') || (legalName && legalName.toLowerCase().includes('milla'));
    const isHorizon = companyId.includes('002') || (legalName && legalName.toLowerCase().includes('horizon'));
    const isApexDelaware = companyId.includes('003') || (legalName && legalName.toLowerCase().includes('delaware'));

    let allTx: BankFeedTransaction[] = [];

    if (isMilla) {
      allTx = [
        // 2021
        {
          id: 'bnk-mila-2021-01',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2021-11-15',
          amount: 5008.98,
          rawDescription: 'STRIPE TRANSFER CLIENT INVOICE GA-001',
          payeeOrMerchant: 'Commercial Cleaning Client Payout',
          categorySuggested: 'Cleaning & Janitorial Revenue',
          suggestedAccountCode: '4010',
          fitId: 'FIT-TRUIST-2021-01',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2021-01',
          matchExplanation: 'Conciliado com Contratos Iniciais de Limpeza 2021 ($5.008,98)',
        },

        // 2022
        {
          id: 'bnk-mila-2022-01',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2022-01-01',
          amount: 115000.00,
          rawDescription: 'WIRE TRANSFER MEMBER CAPITAL CONTRIBUTION',
          payeeOrMerchant: 'Milla Maid Partners Capital',
          categorySuggested: 'Members Capital Account',
          suggestedAccountCode: '3010',
          fitId: 'FIT-TRUIST-2022-01',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2022-01',
          matchExplanation: 'Conciliado com Aporte de Capital dos Sócios ($115.000,00)',
        },
        {
          id: 'bnk-mila-2022-02',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2022-01-10',
          amount: -48500.00,
          rawDescription: 'COMMERCIAL AUTO FLEET & EXTRACTORS ATLANTA GA',
          payeeOrMerchant: 'Commercial Vans & Equipment',
          categorySuggested: 'Fleet Cleaning Vans & Equipment',
          suggestedAccountCode: '1510',
          fitId: 'FIT-TRUIST-2022-02',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2022-02',
          matchExplanation: 'Conciliado com Aquisição de Frota e Vans ($48.500,00)',
        },
        {
          id: 'bnk-mila-2022-03',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2022-06-30',
          amount: 342851.75,
          rawDescription: 'CLIENT PAYMENTS BATCH STRIPE/ACH GEORGIA',
          payeeOrMerchant: 'Cleaning Clients Batch Settlement',
          categorySuggested: 'Cleaning & Janitorial Revenue',
          suggestedAccountCode: '4010',
          fitId: 'FIT-TRUIST-2022-03',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2022-03',
          matchExplanation: 'Conciliado com Faturamento de Serviços 2022 ($342.851,75)',
        },
        {
          id: 'bnk-mila-2022-04',
          institutionName: 'JPMorgan Chase (Georgia)',
          accountNumberMasked: '••••4418',
          date: '2022-12-15',
          amount: -3000.00,
          rawDescription: 'DIRECT DEPOSIT PAYROLL W-2 CREW GUSTO',
          payeeOrMerchant: 'Gusto Payroll W-2 Wages',
          categorySuggested: 'Direct Labor W-2 Wages',
          suggestedAccountCode: '5020',
          fitId: 'FIT-CHASE-2022-04',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2022-04',
          matchExplanation: 'Conciliado com Folha de Pagamento W-2 ($3.000,00)',
        },
        {
          id: 'bnk-mila-2022-05',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2022-12-20',
          amount: -40617.90,
          rawDescription: 'ECOLAB CHEMICALS & CHEVRON FLEET FUEL GA',
          payeeOrMerchant: 'Ecolab & Chevron Fleet Services',
          categorySuggested: 'Vehicle & Cleaning Supplies',
          suggestedAccountCode: '6040',
          fitId: 'FIT-TRUIST-2022-05',
          status: 'RULE_MATCH_FOUND',
          matchConfidence: 98,
          matchedJournalEntryId: 'JE-MILA-2022-05',
          matchExplanation: 'Conciliado com Frota e Insumos Químicos 2022 ($40.617,90)',
        },
        {
          id: 'bnk-mila-2022-06',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2022-12-31',
          amount: -40088.01,
          rawDescription: 'ONLINE TRANSFER TO PARTNER PERSONAL ACCT',
          payeeOrMerchant: 'Partner Profit Distribution (Draws)',
          categorySuggested: 'Partner Draws',
          suggestedAccountCode: '3030',
          fitId: 'FIT-TRUIST-2022-06',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2022-07',
          matchExplanation: 'Conciliado com Retiradas de Sócios 2022 ($40.088,01)',
        },

        // 2023
        {
          id: 'bnk-mila-2023-01',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2023-06-30',
          amount: 477370.70,
          rawDescription: 'MERCHANT SETTLEMENT BATCH COMMERCIAL CLIENTS',
          payeeOrMerchant: 'Commercial Clients 2023 Payouts',
          categorySuggested: 'Cleaning & Janitorial Revenue',
          suggestedAccountCode: '4010',
          fitId: 'FIT-TRUIST-2023-01',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2023-01',
          matchExplanation: 'Conciliado com Receitas de Serviços 2023 ($477.370,70)',
        },
        {
          id: 'bnk-mila-2023-02',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2023-12-15',
          amount: -376986.76,
          rawDescription: 'ACH DIRECT PAY 1099 CONTRACTORS BATCH GA',
          payeeOrMerchant: '1099 Subcontractors Crew',
          categorySuggested: 'Subcontractor Labor 1099',
          suggestedAccountCode: '5010',
          fitId: 'FIT-TRUIST-2023-02',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2023-02',
          matchExplanation: 'Conciliado com Prestadores de Serviços 1099 ($376.986,76)',
        },
        {
          id: 'bnk-mila-2023-03',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2023-12-20',
          amount: -30144.95,
          rawDescription: 'FLEET FUEL & CONSUMABLE SUPPLIES BATCH',
          payeeOrMerchant: 'Vehicle & Supply Operations',
          categorySuggested: 'Vehicle & Supplies Expense',
          suggestedAccountCode: '6040',
          fitId: 'FIT-TRUIST-2023-03',
          status: 'RULE_MATCH_FOUND',
          matchConfidence: 96,
          matchedJournalEntryId: 'JE-MILA-2023-03',
          matchExplanation: 'Conciliado com Despesas de Frota ($30.144,95)',
        },
        {
          id: 'bnk-mila-2023-04',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2023-12-31',
          amount: -62092.05,
          rawDescription: 'PARTNER PROFIT DISTRIBUTION WIRE TRANSFER',
          payeeOrMerchant: 'Partner Profit Distributions (Draws)',
          categorySuggested: 'Partner Draws',
          suggestedAccountCode: '3030',
          fitId: 'FIT-TRUIST-2023-04',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2023-04',
          matchExplanation: 'Conciliado com Distribuição de Lucros 2023 ($62.092,05)',
        },

        // 2024
        {
          id: 'bnk-mila-2024-01',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2024-06-30',
          amount: 412313.30,
          rawDescription: 'STRIPE & CLIENT RETAINER SETTLEMENTS 2024',
          payeeOrMerchant: 'Commercial Client Receipts 2024',
          categorySuggested: 'Cleaning & Janitorial Revenue',
          suggestedAccountCode: '4010',
          fitId: 'FIT-TRUIST-2024-01',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2024-01',
          matchExplanation: 'Conciliado com Faturamento Anual 2024 ($412.313,30)',
        },
        {
          id: 'bnk-mila-2024-02',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2024-12-15',
          amount: -169938.00,
          rawDescription: 'ACH DIRECT PAY 1099 INDEPENDENT CONTRACTORS',
          payeeOrMerchant: '1099 Subcontractors Team',
          categorySuggested: 'Subcontractor Labor 1099',
          suggestedAccountCode: '5010',
          fitId: 'FIT-TRUIST-2024-02',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2024-02',
          matchExplanation: 'Conciliado com Honorários 1099 2024 ($169.938,00)',
        },
        {
          id: 'bnk-mila-2024-03',
          institutionName: 'JPMorgan Chase (Georgia)',
          accountNumberMasked: '••••4418',
          date: '2024-12-20',
          amount: -141023.00,
          rawDescription: 'GUSTO PAYROLL DIRECT DEPOSIT W-2 SALARIES',
          payeeOrMerchant: 'W-2 Direct Labor Wages',
          categorySuggested: 'Direct Labor W-2 Wages',
          suggestedAccountCode: '5020',
          fitId: 'FIT-CHASE-2024-03',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2024-03',
          matchExplanation: 'Conciliado com Folha de Salários W-2 ($141.023,00)',
        },
        {
          id: 'bnk-mila-2024-04',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2024-12-28',
          amount: -60484.00,
          rawDescription: 'WIRE TRANSFER LEGAL CPA AUDIT CONSULTING',
          payeeOrMerchant: 'Legal & CPA Accounting Counsel',
          categorySuggested: 'Legal & Accounting Professional Fees',
          suggestedAccountCode: '6010',
          fitId: 'FIT-TRUIST-2024-04',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2024-04',
          matchExplanation: 'Conciliado com Honorários Jurídicos e CPA ($60.484,00)',
        },
        {
          id: 'bnk-mila-2024-05',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2024-12-31',
          amount: -61431.37,
          rawDescription: 'FLEET FUEL, REPAIRS & COMMERCIAL CHEMICALS',
          payeeOrMerchant: 'Chevron Fleet & Ecolab Chemicals',
          categorySuggested: 'Vehicle & Supplies Expense',
          suggestedAccountCode: '6040',
          fitId: 'FIT-TRUIST-2024-05',
          status: 'RULE_MATCH_FOUND',
          matchConfidence: 97,
          matchedJournalEntryId: 'JE-MILA-2024-05',
          matchExplanation: 'Conciliado com Despesas de Frota e Manutenção ($61.431,37)',
        },
        {
          id: 'bnk-mila-2024-06',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2024-12-31',
          amount: -45966.94,
          rawDescription: 'PARTNER DRAW DISTRIBUTIONS TRUIST TRANSFER',
          payeeOrMerchant: 'Partner Profit Distributions (Draws)',
          categorySuggested: 'Partner Draws',
          suggestedAccountCode: '3030',
          fitId: 'FIT-TRUIST-2024-06',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2024-06',
          matchExplanation: 'Conciliado com Distribuição aos Sócios 2024 ($45.966,94)',
        },

        // 2025
        {
          id: 'bnk-mila-2025-01',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2025-06-30',
          amount: 364061.65,
          rawDescription: 'STRIPE & DIRECT ACH COMMERCIAL CLEANING RECEIPTS',
          payeeOrMerchant: 'Commercial Janitorial Clients (Georgia)',
          categorySuggested: 'Cleaning & Janitorial Revenue',
          suggestedAccountCode: '4010',
          fitId: 'FIT-TRUIST-2025-01',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2025-01',
          matchExplanation: 'Conciliado com Faturamento à Vista 2025 ($364.061,65)',
        },
        {
          id: 'bnk-mila-2025-02',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2025-12-15',
          amount: -108921.00,
          rawDescription: 'ACH DIRECT PAY 1099 INDEPENDENT CONTRACTORS',
          payeeOrMerchant: '1099 Independent Contractors Crew',
          categorySuggested: 'Subcontractor Labor 1099',
          suggestedAccountCode: '5010',
          fitId: 'FIT-TRUIST-2025-02',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2025-03',
          matchExplanation: 'Conciliado com Prestadores 1099 ($108.921,00)',
        },
        {
          id: 'bnk-mila-2025-03',
          institutionName: 'JPMorgan Chase (Georgia)',
          accountNumberMasked: '••••4418',
          date: '2025-12-20',
          amount: -108667.00,
          rawDescription: 'GUSTO/ADP DIRECT DEPOSIT PAYROLL W-2 WAGES',
          payeeOrMerchant: 'Direct Labor W-2 Crew',
          categorySuggested: 'Direct Labor W-2 Wages',
          suggestedAccountCode: '5020',
          fitId: 'FIT-CHASE-2025-03',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2025-04',
          matchExplanation: 'Conciliado com Salários W-2 ($108.667,00)',
        },
        {
          id: 'bnk-mila-2025-04',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2025-12-28',
          amount: -77606.00,
          rawDescription: 'WIRE TRANSFER LEGAL COUNSEL & CPA SERVICES',
          payeeOrMerchant: 'Legal & Accounting Professional Fees',
          categorySuggested: 'Legal & Accounting Professional Fees',
          suggestedAccountCode: '6010',
          fitId: 'FIT-TRUIST-2025-04',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2025-05',
          matchExplanation: 'Conciliado com Honorários Jurídicos e CPA ($77.606,00)',
        },
        {
          id: 'bnk-mila-2025-05',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2025-12-31',
          amount: -25082.00,
          rawDescription: 'WEX FLEET CHEVRON FUEL & ROAD SERVICES GA',
          payeeOrMerchant: 'Chevron & WEX Fleet Solutions',
          categorySuggested: 'Vehicle, Fuel & Road Services',
          suggestedAccountCode: '6040',
          fitId: 'FIT-TRUIST-2025-05',
          status: 'RULE_MATCH_FOUND',
          matchConfidence: 98,
          matchedJournalEntryId: 'JE-MILA-2025-06',
          matchExplanation: 'Conciliado com Despesas de Frota ($25.082,00)',
        },
        {
          id: 'bnk-mila-2025-06',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2025-12-31',
          amount: -32440.00,
          rawDescription: 'ONLINE TRANSFER PARTNER PROFIT DISTRIBUTIONS',
          payeeOrMerchant: 'Partner Profit Distributions (Draws)',
          categorySuggested: 'Partner Draws',
          suggestedAccountCode: '3030',
          fitId: 'FIT-TRUIST-2025-06',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2025-09',
          matchExplanation: 'Conciliado com Distribuição de Lucros 2025 ($32.440,00)',
        },

        // 2026 YTD
        {
          id: 'bnk-mila-2026-01',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2026-04-30',
          amount: 209750.73,
          rawDescription: 'STRIPE CLIENT INVOICE RECEIPTS YTD ATLANTA',
          payeeOrMerchant: 'Commercial Janitorial Clients YTD',
          categorySuggested: 'Cleaning & Janitorial Revenue',
          suggestedAccountCode: '4010',
          fitId: 'FIT-TRUIST-2026-01',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2026-01',
          matchExplanation: 'Conciliado com Receitas 2026 YTD ($209.750,73)',
        },
        {
          id: 'bnk-mila-2026-02',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2026-06-15',
          amount: -45000.00,
          rawDescription: 'ACH DIRECT PAY 1099 CONTRACTORS 2026',
          payeeOrMerchant: '1099 Subcontractor Crew',
          categorySuggested: 'Subcontractor Labor 1099',
          suggestedAccountCode: '5010',
          fitId: 'FIT-TRUIST-2026-02',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2026-02',
          matchExplanation: 'Conciliado com Subcontratados 1099 ($45.000,00)',
        },
        {
          id: 'bnk-mila-2026-03',
          institutionName: 'JPMorgan Chase (Georgia)',
          accountNumberMasked: '••••4418',
          date: '2026-07-20',
          amount: -53420.00,
          rawDescription: 'GUSTO DIRECT DEPOSIT W-2 SALARIES',
          payeeOrMerchant: 'Direct Labor W-2 Crew',
          categorySuggested: 'Direct Labor W-2 Wages',
          suggestedAccountCode: '5020',
          fitId: 'FIT-CHASE-2026-03',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2026-03',
          matchExplanation: 'Conciliado com Salários W-2 ($53.420,00)',
        },
        {
          id: 'bnk-mila-2026-04',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2026-08-15',
          amount: -21000.00,
          rawDescription: 'ECOLAB CHEMICALS & CPA CONSULTING SERVICES',
          payeeOrMerchant: 'Operations & Accounting Counsel',
          categorySuggested: 'General & Operations SG&A',
          suggestedAccountCode: '6010',
          fitId: 'FIT-TRUIST-2026-04',
          status: 'RULE_MATCH_FOUND',
          matchConfidence: 95,
          matchedJournalEntryId: 'JE-MILA-2026-04',
          matchExplanation: 'Conciliado com Honorários e Insumos ($21.000,00)',
        },
        {
          id: 'bnk-mila-2026-05',
          institutionName: 'Truist Bank (Commercial)',
          accountNumberMasked: '••••9102',
          date: '2026-08-20',
          amount: -18000.00,
          rawDescription: 'PARTNER DRAW DISTRIBUTIONS 2026 YTD',
          payeeOrMerchant: 'Partner Profit Distributions (Draws)',
          categorySuggested: 'Partner Draws',
          suggestedAccountCode: '3030',
          fitId: 'FIT-TRUIST-2026-05',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchedJournalEntryId: 'JE-MILA-2026-05',
          matchExplanation: 'Conciliado com Retiradas de Sócios 2026 ($18.000,00)',
        },
      ];
    } else if (isHorizon) {
      allTx = [
        {
          id: 'bnk-hor-2026-01',
          institutionName: 'Mercury Bank (Treasury)',
          accountNumberMasked: '••••1029',
          date: '2026-01-01',
          amount: 210000.00,
          rawDescription: 'FOUNDERS INITIAL CAPITAL CONTRIBUTION WIRE',
          payeeOrMerchant: 'Horizon Founders Capital',
          categorySuggested: 'Common Stock & Paid-in Capital',
          suggestedAccountCode: '3010',
          fitId: 'FIT-MERCURY-01',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchExplanation: 'Aporte de Capital Inicial Horizon ($210.000,00)',
        },
        {
          id: 'bnk-hor-2026-02',
          institutionName: 'Mercury Bank (Treasury)',
          accountNumberMasked: '••••1029',
          date: '2026-03-31',
          amount: 172000.00,
          rawDescription: 'STRIPE PAYOUT SAAS SUBSCRIPTIONS API Q1',
          payeeOrMerchant: 'Stripe SaaS Subscription Billing',
          categorySuggested: 'SaaS Subscription Revenue',
          suggestedAccountCode: '4010',
          fitId: 'FIT-MERCURY-02',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchExplanation: 'Receita de Assinaturas SaaS ($172.000,00)',
        },
        {
          id: 'bnk-hor-2026-03',
          institutionName: 'Mercury Bank (Treasury)',
          accountNumberMasked: '••••1029',
          date: '2026-03-31',
          amount: -48000.00,
          rawDescription: 'AMAZON WEB SERVICES AWS INFRASTRUCTURE',
          payeeOrMerchant: 'Amazon Web Services (AWS Cloud)',
          categorySuggested: 'Cloud Hosting & Servers',
          suggestedAccountCode: '5010',
          fitId: 'FIT-MERCURY-03',
          status: 'RULE_MATCH_FOUND',
          matchConfidence: 98,
          matchExplanation: 'Servidores e Nuvem AWS ($48.000,00)',
        },
      ];
    } else {
      // Default: Apex CleanOps (TX)
      allTx = [
        {
          id: 'bnk-tx-001',
          institutionName: 'JPMorgan Chase (Texas)',
          accountNumberMasked: '••••4819',
          date: '2026-01-01',
          amount: 325000.00,
          rawDescription: 'CAPITAL CONTRIBUTION WIRE TEXAS LLC',
          payeeOrMerchant: 'Members Capital Contribution',
          categorySuggested: 'Members Capital Account',
          suggestedAccountCode: '3010',
          fitId: 'FIT-CHASE-01',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchExplanation: 'Aporte de Capital Inicial Apex TX ($325.000,00)',
        },
        {
          id: 'bnk-tx-002',
          institutionName: 'JPMorgan Chase (Texas)',
          accountNumberMasked: '••••4819',
          date: '2026-03-31',
          amount: 140000.00,
          rawDescription: 'COMMERCIAL JANITORIAL CLIENTS ACH BATCH',
          payeeOrMerchant: 'Commercial Janitorial Sales',
          categorySuggested: 'Commercial Janitorial Sales',
          suggestedAccountCode: '4010',
          fitId: 'FIT-CHASE-02',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchExplanation: 'Faturamento de Serviços de Limpeza ($140.000,00)',
        },
        {
          id: 'bnk-tx-003',
          institutionName: 'JPMorgan Chase (Texas)',
          accountNumberMasked: '••••4819',
          date: '2026-03-31',
          amount: -45000.00,
          rawDescription: 'DIRECT LABOR PAYROLL W-2 CREW',
          payeeOrMerchant: 'W-2 Cleaning Crew Payroll',
          categorySuggested: 'Direct Labor Salaries',
          suggestedAccountCode: '5010',
          fitId: 'FIT-CHASE-03',
          status: 'EXACT_MATCH_FOUND',
          matchConfidence: 100,
          matchExplanation: 'Folha de Salários W-2 ($45.000,00)',
        },
      ];
    }

    // Filtragem rigorosa por ano e meses selecionados
    if (fiscalYear) {
      return allTx.filter((t) => {
        const dStr = typeof t.date === 'string' ? t.date : (t.date as any).toISOString().split('T')[0];
        const y = parseInt(dStr.substring(0, 4), 10);
        const m = parseInt(dStr.substring(5, 7), 10);

        if (y !== fiscalYear) return false;
        if (selectedMonths && selectedMonths.length > 0 && !selectedMonths.includes(m)) return false;
        return true;
      });
    }

    return allTx;
  }
}
